### ISSUE TITLE
Labeling Limbs in Hominoid Rig

### ISSUE THREAD

**Issue by EJames3** [RxLaboratory/DuAEF#35]
A Feature Request/ Bug report.   When  you create a Hominoid rig in Duik Bassel.2 v16.230  It labels  the control layers R and L  for the R and L Limbs  "Hand R Hand L"  and  "Foot R and Foot L"  However the control layers are  not Labeled for R and L limbs
the Structures for the L side are named with just the body part "S | Hand " and  "S | Forearm" etc.
The Structures for the R side are named wit a  "2" after them  "S | Hand 2"  and  "S | Forearm 2" etc
This makes it unnecessarily confusing to set up a character.
If you could just label the Structures wit R and L it would be much easier to do setup   "S | Hand R" and   "S | Hand L"  etc.

**Comment by Nico-Duduf** [comment]
That's done in Duik 17 ;)
Available soon!
